spring:
  main:
    allow-circular-references: true
  application:
    name: authentication-service
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/authentication-service?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:toor}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 2000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        jdbc:
          batch_size: 50
          fetch_size: 50

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
server:
  port: ${PORT:8080}
  error:
    include-stacktrace: always
    include-message: always