spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: pass
    password: pass
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  main:
    allow-circular-references: true
  application:
    name: authentication-service
  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: America/Guayaquil
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication-service
    username: postgres
    password: postgres
    hikari:
      data-source-properties:
        serverTimezone: America/Guayaquil
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 5000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: none # Cambia a 'update', 'create', o 'create-drop' según tu necesidad
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        jdbc:
          time_zone: UTC
          batch_size: 50
          fetch_size: 50

  flyway:
    enabled: true
    connect-retries: 3
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: ${PORT:8080}
  error:
    include-stacktrace: always
    include-message: always
app:
  secret:
    key: pass
  time:
    extra: 31 #dias